issue_scenarios = [
    # Compute Services
    {"product": "Amazon EC2", "issue_type": "Instance Connectivity"},
    {"product": "Amazon EC2", "issue_type": "Auto Scaling Configuration"},
    {"product": "Amazon EC2", "issue_type": "Reserved Instance Billing"},
    {"product": "Amazon ECS", "issue_type": "Container Deployment Failure"},
    {"product": "Amazon ECS", "issue_type": "Task Definition Errors"},
    {"product": "Amazon EKS", "issue_type": "Kubernetes Version Upgrade"},
    {"product": "Amazon EKS", "issue_type": "Node Group Scaling"},
    {"product": "AWS Lambda", "issue_type": "Function Timeout"},
    {"product": "AWS Lambda", "issue_type": "Cold Start Latency"},
    {"product": "AWS Lambda", "issue_type": "Memory Allocation"},
    {"product": "AWS Fargate", "issue_type": "Task Resource Constraints"},
    # Storage Services
    {"product": "Amazon S3", "issue_type": "Access Permissions"},
    {"product": "Amazon S3", "issue_type": "Bucket Policy Configuration"},
    {"product": "Amazon S3", "issue_type": "Cross-Region Replication"},
    {"product": "Amazon EBS", "issue_type": "Volume Performance"},
    {"product": "Amazon EBS", "issue_type": "Snapshot Creation Failure"},
    {"product": "Amazon EFS", "issue_type": "Mount Target Connectivity"},
    {"product": "AWS Backup", "issue_type": "Backup Job Failure"},
    # Database Services
    {"product": "Amazon RDS", "issue_type": "Database Connection"},
    {"product": "Amazon RDS", "issue_type": "Performance Insights"},
    {"product": "Amazon RDS", "issue_type": "Backup Restoration"},
    {"product": "Amazon Aurora", "issue_type": "Cluster Failover"},
    {"product": "Amazon Aurora", "issue_type": "Reader Endpoint Latency"},
    {"product": "Amazon DynamoDB", "issue_type": "Provisioned Throughput"},
    {"product": "Amazon DynamoDB", "issue_type": "Global Table Replication"},
    {"product": "Amazon Redshift", "issue_type": "Query Performance"},
    {"product": "Amazon Redshift", "issue_type": "Connection Issue"},
    {"product": "Amazon Redshift", "issue_type": "Cluster Resize"},
    {"product": "Amazon ElastiCache", "issue_type": "Cache Hit Rate"},
    {"product": "Amazon DocumentDB", "issue_type": "Compatibility Issues"},
    # Analytics Services
    {"product": "Amazon Athena", "issue_type": "Query Timeout"},
    {"product": "Amazon EMR", "issue_type": "Cluster Termination"},
    {"product": "Amazon Kinesis", "issue_type": "Shard Management"},
    {"product": "Amazon Kinesis", "issue_type": "Data Stream Throttling"},
    {"product": "AWS Glue", "issue_type": "ETL Job Failure"},
    {"product": "AWS Glue", "issue_type": "Crawler Configuration"},
    {"product": "Amazon OpenSearch Service", "issue_type": "Cluster Stability"},
    {"product": "Amazon QuickSight", "issue_type": "Dashboard Rendering"},
    {"product": "AWS Data Pipeline", "issue_type": "Pipeline Activation"},
    # Machine Learning Services
    {"product": "Amazon SageMaker", "issue_type": "Model Deployment"},
    {"product": "Amazon SageMaker", "issue_type": "Training Job Resources"},
    {"product": "Amazon Comprehend", "issue_type": "Entity Recognition Accuracy"},
    {"product": "Amazon Rekognition", "issue_type": "Image Analysis Results"},
    {"product": "Amazon Textract", "issue_type": "Document Processing Errors"},
    # Networking Services
    {"product": "Amazon VPC", "issue_type": "Subnet Configuration"},
    {"product": "Amazon VPC", "issue_type": "NAT Gateway Failure"},
    {"product": "AWS Direct Connect", "issue_type": "Connection Stability"},
    {"product": "Elastic Load Balancing", "issue_type": "Health Check Configuration"},
    {"product": "Amazon CloudFront", "issue_type": "Cache Behavior"},
    {"product": "Amazon Route 53", "issue_type": "DNS Resolution"},
    {"product": "AWS Global Accelerator", "issue_type": "Endpoint Routing"},
    # Security Services
    {"product": "AWS IAM", "issue_type": "Permission Boundaries"},
    {"product": "AWS IAM", "issue_type": "Role Assumption"},
    {"product": "Amazon Cognito", "issue_type": "User Pool Authentication"},
    {"product": "AWS WAF", "issue_type": "Rule Evaluation"},
    {"product": "AWS Shield", "issue_type": "DDoS Protection Configuration"},
    {"product": "AWS KMS", "issue_type": "Key Rotation"},
    {"product": "AWS Secrets Manager", "issue_type": "Secret Retrieval"},
    # Developer Tools
    {"product": "AWS CodePipeline", "issue_type": "Pipeline Execution"},
    {"product": "AWS CodeBuild", "issue_type": "Build Environment"},
    {"product": "AWS CodeDeploy", "issue_type": "Deployment Configuration"},
    {"product": "AWS CloudFormation", "issue_type": "Stack Creation Failure"},
    {"product": "AWS CloudFormation", "issue_type": "Resource Rollback"},
    # Management Services
    {"product": "AWS CloudWatch", "issue_type": "Alarm Configuration"},
    {"product": "AWS CloudWatch", "issue_type": "Log Insights Query"},
    {"product": "AWS CloudTrail", "issue_type": "Event Logging"},
    {"product": "AWS Config", "issue_type": "Compliance Rules"},
    {"product": "AWS Systems Manager", "issue_type": "Patch Management"},
    {"product": "AWS Organizations", "issue_type": "Service Control Policies"},
    # Integration Services
    {"product": "Amazon SNS", "issue_type": "Topic Delivery"},
    {"product": "Amazon SQS", "issue_type": "Message Visibility"},
    {"product": "Amazon EventBridge", "issue_type": "Event Pattern Matching"},
    {"product": "AWS Step Functions", "issue_type": "State Machine Execution"},
    {"product": "Amazon MQ", "issue_type": "Broker Connectivity"},
    # Containers and Serverless
    {"product": "AWS App Runner", "issue_type": "Service Deployment"},
    {"product": "AWS Batch", "issue_type": "Job Queue Priority"},
    {"product": "Amazon ECR", "issue_type": "Image Scanning"},
    # Custom/Specialized Services
    {"product": "Cloud Analytics Dashboard", "issue_type": "Performance Issue"},
    {"product": "Cloud Analytics Dashboard", "issue_type": "Data Visualization Error"},
    {"product": "Data Pipeline Service", "issue_type": "Integration Error"},
    {"product": "Data Pipeline Service", "issue_type": "Configuration Problem"},
]
